### ISSUE TITLE
Write endpoint for user login

### ISSUE THREAD

**Issue by josarlo84** [jak103/powerplay#109]
The backend team needs to write the specification and endpoint for allowing user to login.  This ticket does not include validating/authenticating the user, just setting up the endpoint.

**Comment by josarlo84** [comment]
Example is found in backend/server/api/user/user.go file

**Comment by DaffoDyl** [comment]
Assign to me

**Comment by josarlo84** [comment]
Likely mostly implemented.  Dylan is going to figure out what else is needed to resolve this issue 100%

**Comment by DaffoDyl** [comment]
@josarlo84 As far as I can tell Jacob finished up this task in class last week, I though we still needed to do the user lookup as well, but looking at it now thats been done as well.
