### ISSUE TITLE
ADD: Add a README.md in the Backend section of the code.

### ISSUE THREAD

**Issue by tannerwheeler** [jak103/powerplay#120]
GIVEN: As a developer.
WHEN: When looking at the backend section of the code.
THEN: I should see a README.md file with instructions to make commands and how to add an endpoint.

__Acceptance Criteria__
-

**Comment by Westainly** [comment]
I can take this ticket I think.

Do we want to have generic code blocks in here that can be copy-pasted for GET and POST and things like that? Or are we thinking to just have a checklist of things to do when adding an endpoint.

**Comment by Westainly** [comment]
Talking with @Skylude on this:
Create and link to README files within the /backend and the /frontend and /app and so on for each team from the top layer README file.
The contents of the /frontend/README and /app/README and so forth will be up to those teams to fill out.
This ticket will be for the /backend/README.md file and adding in the backend related documentations.

The top layer README will still contatin the helpful make commands like nuke-migrations and go tests as well as a few additional commands for seeding the database and so forth that will be added later on.
