### ISSUE TITLE
ADD: Venue POST and GET Endpoints + Database Table

### ISSUE THREAD

**Issue by tannerwheeler** [jak103/powerplay#122]
GIVEN: I am an admin.
WHEN: I want to find or create the venues available for games.
THEN: Then I can do a POST to create a new venue or a GET to find all available venues.

__Acceptance Criteria__
- Inherit from DBModel
- All ID variables of the model, if any, need to be of type `uint`.
- The name of the Venue
- The address of the Venue as type string
- The Locker Rooms of the Venue as type slice of strings
- API endpoint for venues that returns all venues
  - In the folder /backend/internal/server/apis the file venues.go should exist in the folder stats
- Endpoint for venues
- Rapidocs implemented for venues endpoint

**Comment by OughtNaut** [comment]
I'll take this
