### ISSUE TITLE
ADD: Logo POST and GET endpoint + Database Table

### ISSUE THREAD

**Issue by jak103** [jak103/powerplay#126]
The post should take an image and upload it to the logo table. 
The get should take an ID and fetch it from the table and return it as an image. 

GIVEN: I'm logged into the application as a Captain or Admin configuring teams
WHEN: I click on "Logos"
THEN: I can see the available Logos

__Acceptance Criteria__
- Inherit from DBModel
- Contains an Image
- API endpoint for logos
  - In the folder /backend/internal/server/apis the file logos.go should exist in the folder user
- Rapidocs implemented for logo endpoint

**Comment by ryanbarlow1** [comment]
@tannerwheeler Can you assign this to me?
