### ISSUE TITLE
ENHANCEMENT: POST doc GET and POST items should be self explanitory

### ISSUE THREAD

**Issue by tannerwheeler** [jak103/powerplay#132]
GIVEN: I am a developer.
WHEN: I am looking at the POST Doc information at localhost:9002/docs.
THEN: The GET items do not have the word 'get' in the message and the POST items do not have the word 'post' in the message.

__Acceptance Criteria__
- The GET items do not have the word 'get' in the message.
- The POST items do not have the word 'post' in the message.

**Comment by ethanchristensen01** [comment]
Just to clarify, the GET and POST items *should* or *should not* have the word 'get'/'post' in the message?

**Comment by tannerwheeler** [comment]
@ethanchristensen01 the GET and POST items _should not_ have the word 'get'/'post' in the message. As Dr. Christensen pointed out to us during our demo, the word POST and GET are on the Rapidocs page, so for example we would see something like:
`GET` All Games
`POST` Create a Game
