### ISSUE TITLE
ADD: Penalty Type POST and PUT Endpoints

### ISSUE THREAD

**Issue by tannerwheeler** [jak103/powerplay#178]
GIVEN: I am an admin for a hockey league.
WHEN: I need to add or modify the Penalty Types for the League.
THEN: I am able to change the Penalty Types by ID or add new Penalty Types to the database.

__Acceptance Criteria__
- The POST Endpoint can be demonstrated on the Rapidocs page `localhost:9002/docs`.
- The PUT Endpoint can be demonstrated on the Rapidocs page `localhost:9002/docs`.

Tests for the Endpoints exists and run verifying the Endpoints work:
- For POST of Penalty Types
    - Input: Correct data for a new Penalty Type. Output: Status Code 200 is returned.
    - Input: Incorrect data for a new Penalty Type. Output: Status Code 400 is returned.
- For PUT of Penalty Type
    - Input: Correct data for getting a Penalty Type by ID. Output: Status Code 200 is returned.
    - Input: Incorrect data for getting a Penalty Type by ID. Output: Status Code 400 is returned.
- Test Passes if all output pass, but Fails if one output fails.

**Comment by ryanbarlow1** [comment]
I can take this on

**Comment by ryanbarlow1** [comment]
@tannerwheeler Can you close this? This was addressed in https://github.com/tannerwheeler/powerplay-backend-stats/pull/29
