### ISSUE TITLE
ADD: Penalties by Game Endpoint

### ISSUE THREAD

**Issue by tannerwheeler** [jak103/powerplay#18]
GIVEN: I’m any user visiting the [[ecclesicehockey.com](http://ecclesicehockey.com/)](http://ecclesicehockey.com) website / app
WHEN: I view the box score details for a specific game
THEN: I can view total penalty minutes and total penalties for the game (per team)

**Acceptance Criteria**
- API Endpoint to GET a list of all penalties per game
    - /games/{id}/penalties
- Tests for getting a list of all penalties per game
- Documentation exists and you can test endpoint within OpenAPI3.0 Spec (port 9001)

**Comment by Skylude** [comment]
Blocked by #19

**Comment by ryanbarlow1** [comment]
@tannerwheeler Can you remove this blocker and assign this to me?

**Comment by ryanbarlow1** [comment]
@tannerwheeler Can you close this? This was addressed in https://github.com/tannerwheeler/powerplay-backend-stats/pull/29
