### ISSUE TITLE
ADD: Penalty POST Endpoint + Database Table

### ISSUE THREAD

**Issue by tannerwheeler** [jak103/powerplay#19]
GIVEN: I’m logged into the application as a scorekeeper and I’m actively scoring a game.
WHEN: A player commits a penalty
THEN: I want to be able to store all the information regarding the penalty.

**Acceptance Criteria**
- Database table exists for Penalty
    - Inherit from DBModel
    - A foreign key back to the player committing the penalty will be stored in the database
    - A foreign key back to the game in which the penalty was created will be stored in the database
    - The period number that the penalty was committed will be stored in the database
        - Will need to check OT rules here
    - A foreign key to the team that committed the penalty
    - A foreign key to the scorekeeper / user that is inputting the data is stored in the database (will be set on the CreatedBy (if it exists)
    - A foreign key to the penalty type stored in the database (DEPENDS ON PenaltyType issue)
    - Duration (if penalty times are NOT standard to each penalty type and can differ this will need to be stored here, otherwise it can be stored on penalty type
    - Time at which the penalty occurred
        - Time can optionally be passed in, otherwise now is used (for active scorekeeping)
        - Time in seconds since period (game?) started
- API endpoint to POST data for a new penalty with it’s associated data
- Test exists for testing POST endpoint to Penalty
- Documentation exists and you can actively test the POST endpoint for Penalty

**Documentation / Notes**

- Need to store all data needed for Penalty Summary section of this page
    - https://www.ecclesicehockey.com/game/show/42280852?subseason=922116&referrer=8386970

**Comment by Skylude** [comment]
Blocked by #20

**Comment by ryanbarlow1** [comment]
PR: https://github.com/tannerwheeler/powerplay-backend-stats/pull/2
