### ISSUE TITLE
ADD: PenaltyType GET Endpoint + Database Table

### ISSUE THREAD

**Issue by tannerwheeler** [jak103/powerplay#20]
GIVEN: I’m logged into the application as a scorekeeper and I’m actively scoring a game.
WHEN: A player commits a penalty
THEN: I want to be able to select from a list of available penalties

**Acceptance Criteria**
- Database table exists for PenaltyType
    - Inherit from DB Model
    - Name
    - Duration (if all penalties of that type always have the same duration — otherwise this would live on the penalty table
    - Level (need to research listed as “Minor” on some, not sure what others are)
- API Endpoint to GET a list of all PenaltyTypes and the associated data
    - /penaltyTypes
- Test exists for testing GET endpoint for PenaltyTypes
- Documentation exists and you can actively test the GET endpoint for PenaltyTypes

**Comment by calebedwards21** [comment]
I can do the the last 3 bullets in the AC if you're ok with that @Skylude?

**Comment by tannerwheeler** [comment]
Merged into the main project.
