### ISSUE TITLE
ADD: Goal POST Endpoint + Database Table

### ISSUE THREAD

**Issue by tannerwheeler** [jak103/powerplay#21]
GIVEN: I’m logged into the application as a scorekeeper and I’m actively scoring a game.
WHEN: A player scores a goal
THEN: I want to be able to store all the information regarding the goal.

Acceptance Criteria
- Database table exists for Goal
   - Inherit from DBModel 
   - A foreign key back to the player scoring the goal will be stored in the database 
   - A foreign key back to the game in which the goal was created will be stored in the database 
   - A foreign key to the team scoring the goal
   - A foreign key to the scorekeeper / user inputting the goal is stored in the database (will be set on the CreatedBy (if it exists))
   - A foreign key to assists associated with the goal
   - The period number the goal was committed will be stored in the database 
       - Will need to check OT rules here 
   - Time at which the goal occurred 
       - Time can optionally be passed in, otherwise now is used (for active scorekeeping) 
       - Time in seconds since period (game?) started
       - (Could be combined with the bullet point above)
   - Was the Goal scored during a PowerPlay
- API endpoint to POST data for a new Goal with it’s associated data 
- Test exists for testing POST endpoint to Goal 
- Documentation exists and you can actively test the POST endpoint for Goal 

Documentation / Notes
- Need to store all data needed for Goal Summary section of this page 
    - https://www.ecclesicehockey.com/game/show/42280852?subseason=922116&referrer=8386970

**Comment by MichaelPHanks** [comment]
Maybe this one should go first
