### ISSUE TITLE
ADD: Teams POST and GET Endpoint + Database Table

### ISSUE THREAD

**Issue by tannerwheeler** [jak103/powerplay#73]
GIVEN: I'm logged into the application as a User
WHEN: I click on "Teams"
THEN: I can see the Teams in a season or league

__Acceptance Criteria__
- Inherit from DBModel
- All ID variables of the model, if any, need to be of type `uint`.
- A CorrelationID of type string
- A LogoID of type string
- A Color of type string
- A foreign key back to the League where the team belongs.
- A foreign key back to the Roster of the team.
- A counter Wins for the number of wins.
- A counter Losses for the number of losses.
- API endpoint for teams that returns all teams
  - In the folder /backend/internal/server/apis the file teams.go should exist in the folder groups
- Endpoint for teams includes roster for the team and the league.
- Rapidocs implemented for teams endpoint

**Comment by ryanc3412** [comment]
I got this one

**Comment by brandonwilliamsk** [comment]
I would like to help with this one and then compare with Ryan if that works!

**Comment by tannerwheeler** [comment]
@brandonwilliamsk it would be good to work through it together too. But I did assign you both to the issue.
