### ISSUE TITLE
ADD: Season POST and GET Endpoint + Database Table

### ISSUE THREAD

**Issue by tannerwheeler** [jak103/powerplay#75]
GIVEN: I'm logged into the application as a Manager or Admin configuring seasons
WHEN: I click on "Seasons"
THEN: I can see the Seasons

__Acceptance Criteria__
- Inherit from DBModel
- All ID variables of the model, if any, need to be of type `uint`.
- The name of the Season
- The time (day, month, year, hour, ...) the seasons Starts
- The time (day, month, year, hour, ...) the seasons Ends
- A slice of type Registration as the variable Registrations
- A slice of type Game as the variable Schedule
- A slice of type League as the variable Leagues
- API endpoint for season that returns all seasons
  - In the folder /backend/internal/server/apis the file seasons.go should exist in the folder `groups`
- Endpoint for seasons includes all associated leagues
- Rapidocs implemented for /seasons endpoint

**Comment by MichaelPHanks** [comment]
I could take a shot at this one

**Comment by MichaelPHanks** [comment]
- API endpoint for /rosters that returns all leagues
- Endpoint for /seasons includes all associated leagues

@tannerwheeler could you expand on these for me? Are these supposed to be seasons instead of leagues?

**Comment by tannerwheeler** [comment]
I changed 'API endpoint for /rosters that returns all leagues'. Rosters should have been seasons.
For the second, you should be able to see all of the Leagues when you look at the season.
Did that help?
