### ISSUE TITLE
ADD: Roster POST and GET Endpoint + Database Table

### ISSUE THREAD

**Issue by tannerwheeler** [jak103/powerplay#77]
GIVEN: I'm logged into the application as a Captain or Admin configuring teams for seasons or games.
WHEN: I click on "Rosters"
THEN: I can see the Roster(s) of the team/teams

__Acceptance Criteria__
- Inherit from DBModel
- All ID variables of the model, if any, need to be of type `uint`.
- A slice of Users associated with this Roster under the variable Players.
- A foreign key back to the User who is the Captain of the Roster.
  - A Captain of type User
    - This should be a foreign key.
  - The CaptainID
- API endpoint for /rosters that returns all rosters
  - In the folder /backend/internal/server/apis the file rosters.go should exist in the folder groups
- Endpoint for /rosters includes all users (players) on each roster
- Rapidocs implemented for /rosters endpoint

**Comment by calebedwards21** [comment]
I can work on this issue @tannerwheeler
