### ISSUE TITLE
BUG: Penalty - Invalid json payload returns 404

### ISSUE THREAD

**Issue by tannerwheeler** [jak103/powerplay#80]
When we pass an invalid json payload to the POST endpoint it just returns a 404 Not Found which is completely unexpected

GIVEN: I am interacting with the Penalty's POST API.
WHEN: I pass invalid json.
THEN: I should receive a 400 (Bad Request) with proper error message.

__Acceptance Criteria__
- Handle in Penalty API POST endpoint if passing invalid types in the json (float property instead of int)
- Handle in Penalty API POST endpoint if passing in malformed json payload

**Comment by tannerwheeler** [comment]
@ryanbarlow1 could you please add the acceptance criteria for this issue. We might need a separate issue about logging.

**Comment by ryanbarlow1** [comment]
@tannerwheeler Can you assign this one to me? I can't change the acceptance criteria myself, but the gist is:

- Handle in Penalty API POST endpoint if passing invalid types in the json (float property instead of int)
- Handle in Penalty API POST endpoint if passing in malformed json payload
