### ISSUE TITLE
Add endpoint for referee rsvp

### ISSUE THREAD

**Issue by funkybooboo** [jak103/powerplay#95]

**Comment by epeterson42** [comment]
Is this different than #86 ?

**Comment by funkybooboo** [comment]
Yes, just because they are signed up doesn't mean they will go, right? If they rsvp and say no, then we know to reach out to a referee pool.

**Comment by epeterson42** [comment]
Oh I see. So I guess my next question is if refs need to rsvp? I thought only players rsvp so the captains can get subs, I don't recall Jacob ever saying anything about refs needing to rsvp. I could be wrong though.
